### ISSUE TITLE
Improve Documentation (user request)

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#103]
1) Step 2 in the instructions say to double click on "no2" in the chain and make changes.  Doing so creates a new no2, and pushes the end to no3.  However, step 3 in the instructions says to double click on No5, but there is no No5.  I do not know whether I should intrepret No5 as a typo that should be No3, or if there are some edits planned that were somehow excluded from the instructions.  I am hoping that there are some missing steps that will help get the audio to sound more natural, or to help the individual syllables to flow into phrases & sentences.

2) I struggled for quite a while to get audio to work at all.  Eventually, I heard audio for only 1 card, then a 2nd, etc.  I figured out through trial and error that you have to select "Edit" -> "Edit Current..." on each card before it will play the audio.  I suspect there may be a better way to get audio to come on for each card, but I didn't see it in the "getaudio.txt" or the instructions at the ".../getit.html" site.  Note that I did try "Fill missing card data" multiple times....it appears that this populates the audio files in the .media directory for the given deck, but doesn't actually start the audio flowing.

**Comment by batterseapower** [comment]
I've fixed problem #2 - it was a bug. Can you fix #1 Nick?

**Comment by Nick3C** [comment]
Done, closing this issue.

I have also moved documentation into the wiki instead of the readme. This still needs formatting tidying (but that has it's own issue tracker)
