### ISSUE TITLE
Bug with Percentage Generation

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#109]
it only works with the western percentage sign, not the Chinese one, i.e. should work with both of these:
  % ％

**Comment by Nick3C** [comment]
It also doesn't work if the percentage is part of a phrase so...
5% - works; but
它占全球产量的5% - doesn't work

**Comment by batterseapower** [comment]
Yeah, none of the number stuff works if it's embedded in a phrase yet. There is a ticket open for that. I'll fix the other issue.

**Comment by batterseapower** [comment]
Support the Chinese % sign. Closed by c43f748ef59bed8744094bd74751d6158d24b2e4

**Comment by batterseapower** [comment]
Done. Do we need support for the chinese double width . in decimals too??

**Comment by Nick3C** [comment]
yep we probably should.
