### ISSUE TITLE
Small delay on lookup

### ISSUE THREAD

**Issue by batterseapower** [batterseapower/pinyin-toolkit#11]
I also notice a new problem when the expression field is left empty there
will be a 0.3 second delay (ish) on change that is not there even during
ordinary lookups

Max says: due to Google translate, probably

**Comment by Nick3C** [comment]
yup, needs to be disabled when blank field. Thought I had done this, but clearly not...

**Comment by Nick3C** [comment]
oops, how do i reopen that?

**Comment by Nick3C** [comment]
this is dealt with by that minor mod I made a while ago that you commented on in the code.
