### ISSUE TITLE
Trad. Hanzi Masking Bug in Preferences Window (very minor)

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#119]
if you select traditional as the preference then the hanzi masking fails to work.

**Comment by Nick3C** [comment]
while we are on the topic they are not "accents" but "tone marks". That is the proper name for them so we should use that. I would be happy with "Tone Marks (accents)" though :)

I would prefer "Tone number" too.

**Comment by batterseapower** [comment]
Change accents -> tone marks and made the preferences preview character change with the character system. Closed by e3492a5d5322616e78e779cd82db745fac34b40e

**Comment by batterseapower** [comment]
I've fixed this by just making the preferences window character change with the character system. There is a question as to whether we want to mask both the simplified and traditional variants of a character from the meaning, though - I haven't implemented /that/.
I've changed that text as well.

**Comment by Nick3C** [comment]
all sounds fine. Perhaps masking can be extended at some future date, but as I am yet to see the issue, even once, I don't think it's worth getting excited about. Things are complex enough already :)
