### ISSUE TITLE
Audio spacing improvements

### ISSUE THREAD

**Issue by batterseapower** [batterseapower/pinyin-toolkit#12]
Look at getting Anki to start loading second audio file before first audio file has finishedplaying as this will dramatically reduce gap between words and make phrass sounds more natural

**Comment by Nick3C** [comment]
For each media pack have a "aprox length" setting. We can use this to work out how much of a delay to put between playing file1 and file2 in a list.

Can't get any better than the media pack I have put together, the limiting factor is not longer the file but the loading time for the media file

**Comment by batterseapower** [comment]
The loading delay is (I guess) a function only of the speed of the users computer, not the particular audio pack. So we should detect and apply this somehow?

Had a look at the Anki source code for sound operations and it doesn't look entirely straightforward.

**Comment by Nick3C** [comment]
sure but I suspect that the bottleneck is disk access. How exactly do the audio routines work? Anki isn't really designed to play multiple audio files on one card so I would guess that it runs the process multiple time (initialise audio, play audio, finish and return) it might be faster if we could pass the audio to it at once and remove the interim shut-down start-up for media playing.

Anyway the gap is very small on my pc, like 0.2 a second, but that is enough to make phrases sound poor. A separate audio plyer solves this.

**Comment by batterseapower** [comment]
Yes, you're right. This is the main loop:

"""
    def run(self):
        while 1:
            time.sleep(0.1)
            if queue:
                path = queue.pop(0)
                retryWait(subprocess.Popen(
                    externalPlayer + [path], startupinfo=si))
            else:
                return
"""

So it basically invokes the player multiple times. The delay will never be better than 50ms on average with this code, due to the sleep() alone, and it's likely to be much worse because Anki spawns the external player once per sound, and process creation is **slow** on Windows.

Probably what is required here is a patch to pass several things to mplayer at once, as you say.

**Comment by Nick3C** [comment]
^_____^
