### ISSUE TITLE
French Should fall back on CEDICT

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#121]
French is meant to be using CEDICT for pinyin isn't it? Otherwise it is almost useless because it can't get sound or pinyin.

**Comment by batterseapower** [comment]
This should definitely work in the new backend (though I'm pretty sure it did before as well).

**Comment by batterseapower** [comment]
I spoke too hastily. I see why it is broken. Fix upcoming...

**Comment by batterseapower** [comment]
Massive refactoring of the way dictionaries are loaded and created, which also makes things a LOT faster. Closed by 915485081de61911ac262e47375c7aadc3f4b58c
