### ISSUE TITLE
Pinyin colorisation eats sandhi colors

### ISSUE THREAD

**Issue by batterseapower** [batterseapower/pinyin-toolkit#124]
Sandhi colors get junked by the colorisation for readings because sandhi aren't marked in the text. I think the best solution is to have the reading coloriser be careful not to overwrite any existing colors in the text, though this will be a bit fiddly.

**Comment by Nick3C** [comment]
doing that will have other consequences, eg losing reformatting of other colours.

Can't we just use the regex to find pinyin instances and then check for a letter "r" to the right. If it is found add a space (then it will be passed normally as erhua).

**Comment by batterseapower** [comment]
Sorry, this ticket is crap. I meant sandhi not erhua. Not sure what I was thinking :-)

**Comment by batterseapower** [comment]
Erhua is actually an issue though, but the fix required is different. I'll open another ticket.

**Comment by Nick3C** [comment]
Ah, that makes more sense and is an altogether harder issue to deal with.

**Comment by batterseapower** [comment]
Preserve HTML colorization throughout the token stream and hence don't overwrite user-supplied colors. Closed by 6fe77bd7b458ed6fe36cd187968108ee81107cb7
