### ISSUE TITLE
Text replacement for Surname XXX in Meaning

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#128]
For our purposes CEDICT's policy of listing eg 汪's meaning as including "surname Wang" is really irritating because it gives the user the pinyin every time.

I propose where the word "surname" is followed by a single word and a line ending we replace the line with: "(a surname)" so that the pinyin isn't revealed.

**Comment by batterseapower** [comment]
Yes, also something I've been thinking about.

**Comment by batterseapower** [comment]
Surname masking. Closed by eb0ec2041d84e089f5c2dec1bc95bc31f5503213
