### ISSUE TITLE
Formatting Improvements in Meaning

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#129]
I have come to the conclusion (through experimentation) that words are much easier to learn if there is one short-main line that you try to remember (even where the word has multiple meaning), rather than trying to remember several or multiple meanings.

I have taken to picking the most important entry in a Meaning and then:
- put it on the top line
- remove it's index number (and reorder the others)
- use a <small> tag to keep the other meaning visible but out of the way

Perhaps we could do this automatically:
1) assume the first line is the most common (per CEDICT rules) and do the above formatting on it
2) add a shortcut that would trigger the current line to be reformatted as first and the other meaning reordered.

Would you like to see a deck with a few sample cards showing what I mean?

**Comment by batterseapower** [comment]
When you say a "tag", are you using <br />?

I also only learn the most frequent meaning, so I'm in agreement that we could do something here. Perhaps it could be another flag to the meaning generation stuff rather than a shortcut, though.

**Comment by batterseapower** [comment]
Ummm... that should say:

```
<br>
```

But Markdown doesn't like thta?

**Comment by Nick3C** [comment]
lol same problem, no i use a 'small' tag. this reduces visibility so that it's not readable from normal viewing distance but if I squint at it I can read it :)

**Comment by Nick3C** [comment]
yes a flag is probably a better idea, maybe:
  {      }

**Comment by Nick3C** [comment]
although we better make the tag customisable or I guarantee we will upset some people who have used those characters for some other purpose.

**Comment by Nick3C** [comment]
Another point, I think that the (1) and (2) should only be used if there are 3 entries (otherwise they can be more of a nuisance than anything else)

Also the top line should be exempt from a number (as it is emphasises). Lower lines could start either (1) or (2), doesn't matter much.

**Comment by batterseapower** [comment]
Yes, I think that if emphasis of the first meaning is turned on then:

1) We only number if we have at least 3 things
2) Displayed numbers start from 2), not 1)

If emphasis is not on then we do everything just like we are currently.

**Comment by Nick3C** [comment]
agree but with minor variation on the final line:
if emphasise is not on then we do things the same except that we only add counters if there are 3 or more (not 2 or more). If there are only 2 the indexes get in the way.

**Comment by batterseapower** [comment]
Hmmm, I'm not sure about that. That behaviour seems too inconsistent to me - and it's easier for you to delete 2 extra numbers than it is for those who want them to add them back in (though only a bit easier, since we have the (n) rewriting feature).

**Comment by batterseapower** [comment]
Well, I've added the feature. However:

1) I didn't add UI to expose the tag change, though it's fully implemented internally. Adding control would just ugly up the dialog box :-). If there is demand, it is easy to add it.
2) I'm still adding numbers if you only have 2 meanings, even in "classic" mode

**Comment by Nick3C** [comment]
great. both sound fine. I'll give it a go.
