### ISSUE TITLE
Switch to SQL Database for dictionaries to Reduce memory usage

### ISSUE THREAD

**Issue by batterseapower** [batterseapower/pinyin-toolkit#13]
Long-term plan to reduce memory usage, simplify code, and enhance overall feature-set.

Would require writing code to import dictionaries so probably best left until an auto-update procedure is devised.

**Comment by Nick3C** [comment]
I had somebody suggest we convert the dictionaries into SQL databases and do queries on them. It sounds like a lot of work and I don't like the idea of losing the ease-of-updates.

**Comment by Nick3C** [comment]
sorry, this is a duplicate. closing
