### ISSUE TITLE
Release 0.05.5

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#133]
I think it would be a good idea to offer a point release for 0.05.5 of our current development tree.

We have fixed quite a few bugs since 0.05 that we should really distribute now rather than waiting for 0.06. The extra features can just be a bonus to users.Documentation for the new features can wait though I guess.

Would that be alright with you?

**Comment by batterseapower** [comment]
Hmmm, if you think it is solid. However, I think the pinyin colorisation on onfocuslost should be turned off by default (change config.py). We really need to fix the sandhi issue with it before it is production-ready.

**Comment by Nick3C** [comment]
Well we know the current code has bugs, but then we also know that 0.05 has bugs. The mass-fill bug being particularly serious. 0.05.5 would therefore seem to be no worse than 0.05 and also adds more features as well as improved internals.

I am just aware that if we don't fix the bugs that were reported in 0.05 we look bad compared to Damien's speediness :) The current workload for 0.06 is likely to be another few months so this will hopefully keep people happy in between.

**Comment by Nick3C** [comment]
we can forget this i think. the changes in database certainly justify a full release
