### ISSUE TITLE
Bug in Pinyin Field Coloriser

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#137]
can't handle "lu:3" style pinyin (which is should because it makes it easy to add the dot marks and because there was a bug with like 0.02 or 0.03 that generated some pinyin in this format and there may be legacy pinyin in decks.)

**Comment by batterseapower** [comment]
Tokenize lu:3 style pinyin correctly. Closed by a00c946df02414ed682aac81756980e659b12ad3
