### ISSUE TITLE
Convert Dictionaries to SQL Database so we can use union on them

### ISSUE THREAD

**Issue by batterseapower** [batterseapower/pinyin-toolkit#14]
Long-term plan to reduce memory usage, simplify code, and enhance overall feature-set.

Would require writing code to import dictionaries so probably best left until an auto-update procedure is devised.

For example, we can use the english dictionary to do a MW lookup even in German, French and other languages

**Comment by batterseapower** [comment]
Sure. I think it would make sense for us to preprocess the dictionaries so we have these files:
    \* dict-pinyin.txt (just the pinyin)
    \* dict-en.txt, dict-fr.txt, dict-de.txt (just the language-specific meanings, excluding measure words)
    \* dict-mws.txt (just the measure words)

Only dict-pinyin.txt would have to include both simplified and traditional characters, all the others could save space by e.g. just including traditional

**Comment by Nick3C** [comment]
if we do this we might as well turn it into SQL. The only real benefit of the current filetypes is that they are standardirsed. If we change that we might as well totally change it.

**Comment by batterseapower** [comment]
Agreed, I think SQL is actually the right way to go right now. Key benefits are:
- Lower memory usage
- Faster loading time for the plugin
- Can easily reuse measure words, pinyin data between languages

**Comment by batterseapower** [comment]
Fixed by cjklib.
