### ISSUE TITLE
Hide 'system' media directory

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#141]
We should hide the system directory in the plugin directory. At the moment it contains a single silence mp3 and it is likely to confuse users.

I think this should be done by looking for "packsettings.ini" in sound pack directories. For this setting we could use something like "displayinprefs=False". The reason I suggest this method is that it opens the door for better control of audio packs in a future-enhanceable way.

For example, it was suggested on the forums that we could have different packs for vocab versus phrases. I am not terribly keen but keeping the door open for such future changes makes sense.

**Comment by batterseapower** [comment]
I've fixed this by moving the file to a "system-media" directory instead. Much (!) easier, and we don't lose anything. In particular, it's not really that useful to create a MediaPack object for the system sounds, because we don't need to chose one from some pinyin.
