### ISSUE TITLE
Latest two versions of pinyin-toolkit don't work on 10.5 due to "logger" import

### ISSUE THREAD

**Issue by jlnr** [batterseapower/pinyin-toolkit#149]
Hello,

When I try to use either of the latest two pinyin-toolkit versions (0.6.3 and the one before) on 10.5 with either the latest stable Anki or the 0.9.9.8.5 snapshot, I get the following error when opening Anki:

An error occurred in a plugin. Please contact the plugin author.
Please do not file a bug report with Anki.

Traceback (most recent call last):
  File "ankiqt/ui/main.pyc", line 2407, in loadPlugins
  File "/Users/jlnr/Library/Application Support/Anki/plugins/Pinyin Toolkit.py", line 29, in 
  File "/Users/jlnr/Library/Application Support/Anki/plugins/pinyin/anki/main.py", line 17, in 
  File "/Users/jlnr/Library/Application Support/Anki/plugins/pinyin/anki/hooks.py", line 9, in 
  File "/Users/jlnr/Library/Application Support/Anki/plugins/pinyin/factproxy.py", line 3, in 
ImportError: No module named logger

By changing line 3 of factproxy.rb to

from logger import log

everything suddenly works again.

I am sorry in advance because I think I must be doing something wrong. I didn't find this issue with the search but can't imagine that only Windows users use the Pinyin Toolkit, and a total showstopper should have been found earlier :)

**Comment by batterseapower** [comment]
Hmm. This doesn't sound right. The third line of factproxy.py should read:

from pinyin.logger import log

I have seen something like this problem reported before - it was caused by Anki not overwriting factproxy.py with the latest version when upgrading from an old version. If this is the problem in this case, then you should be able to fix it by deleting the pinyin/ directory from ~/Library/Application Support/Anki/plugins/ and installing the Toolkit again from the shared plugins screen.

**Comment by jlnr** [comment]
Yes, the line reads like you quoted it. I don't know any python but after looking at other source files, I gave my version a try (removing the "pinyin."), and it worked.

When I install the plugin from inside Anki, Anki overwrites this file with the original version again and it doesn't start anymore.

**Comment by batterseapower** [comment]
Just to check: did you actually delete the pinyin/ folder before you installed the Toolkit again?

**Comment by jlnr** [comment]
Oh, no. I just figured if the file looked like before I changed it the installation should have been able to overwrite stuff. This time I deleted all the pinyin files, reinstalled the PT and it worked. Thanks!

Sorry for the noise, seems to be an Anki bug then :)

**Comment by batterseapower** [comment]
Cool. Thanks!
