### ISSUE TITLE
ImportError: No module named BeautifulSoup

### ISSUE THREAD

**Issue by ghost** [batterseapower/pinyin-toolkit#152]
## I just tried installing the toolkit om Anki 0.9.9.8.5 and received this error message:

An error occurred in a plugin. Please contact the plugin author.
Please do not file a bug report with Anki.

Traceback (most recent call last):
  File "/usr/share/anki/ankiqt/ui/main.py", line 2401, in loadPlugins
    **import**(nopy)
  File "/home/jfca/.anki/plugins/Pinyin Toolkit.py", line 29, in 
    import pinyin.anki.main as main
  File "/home/jfca/.anki/plugins/pinyin/**init**.py", line 23, in 
    import config
  File "/home/jfca/.anki/plugins/pinyin/config.py", line 6, in 
    import dictionaryonline
  File "/home/jfca/.anki/plugins/pinyin/dictionaryonline.py", line 7, in 
    from model import *
  File "/home/jfca/.anki/plugins/pinyin/model.py", line 6, in 
    from BeautifulSoup import BeautifulSoup, Tag
## ImportError: No module named BeautifulSoup

I couldn't find any other references to it so I'm posting now. This is the first plugin I've installed. I'm running Ubuntu 9.1

Thanks

**Comment by ghost** [comment]
I took a look at the code and it seems that the BeautifulSoup source files are not included with the current version of this plugin. I downloaded and extracted the .py module to the main directory and everything seems to be working. Is this package supposed to be included in the vendor's directory?

**Comment by joeyboy** [comment]
I just had the exact same problem. 
Can you pls explain the workaround in more detail?
I located the file BeautifulSoup-3.0.2.py. 
What exactly should I do with it?

**Comment by batterseapower** [comment]
Hi guys,

You are all running Linux, and so you you need to run "sudo apt-get install python-beautifulsoup".

The next version of the Toolkit will tell you to do this explicitly.
