### ISSUE TITLE
Scrolling in Live Preview scrolls the language list

### ISSUE THREAD

**Issue by 2-4601** [batterseapower/pinyin-toolkit#154]
In OS X 10.4.11 and Pinyin Toolkit 0.6.3 when scrolling in Live Preview section of the preferences window it scrolls the language list on the right.

**Comment by 2-4601** [comment]
Forgot to mention that this happens with Anki 0.9.9.8.6 snapshot 2.
(In 0.9.9.8.5 I cannot even access the Pinyin Toolkit preferences. See issue 153. http://github.com/batterseapower/pinyin-toolkit/issues/#issue/153)

**Comment by batterseapower** [comment]
Fixed in master.
