### ISSUE TITLE
Integration with more dictionaries

### ISSUE THREAD

**Issue by batterseapower** [batterseapower/pinyin-toolkit#16]
Consider how other dictionaries can be usefully used.

**Comment by Nick3C** [comment]
Maybe we can use google dicitonary to check before we use google translate: http://www.google.com/dictionary?source=translation&hl=en&q=屡屡&langpair=zh-CN|en

Google translate actually duplicates this, which is irritating in itself (as you get the entry twice)

**Comment by Nick3C** [comment]
My favourite dictionary is here: http://www.nciku.com

I looked at this a little. It uses javacript queries. Might be tricky.

**Comment by Nick3C** [comment]
Wikidictionary, not bad but rather sparse on content. Does have some audio which open the door to retrieval of these and into a sound pack.

http://en.wiktionary.org/wiki/他们 / http://upload.wikimedia.org/wikipedia/commons/Zh-t%C4%81men.ogg

**Comment by Nick3C** [comment]
this has been superseded by the work on link-bar
