### ISSUE TITLE
Error w/fresh install of PTK 0.6.3 plugin on USB Key Drive

### ISSUE THREAD

**Issue by RavinDave** [batterseapower/pinyin-toolkit#162]
ANKI 9.9.9.8.6
Windows XP-Pro SP-3
SanDisk Cruzer 14GB 
Current Active Plugins:
--Basic Chinese Support
--Japanese Support
--JapaneseXtended

ANKI Path:  G:\Anki
Plugin Path:    G:\Anki\ankiconfig\plugins

*nb: Have installed earlier ANKI w/PTK plugin on a Cruzer before with no problems. 

It appears that Damien shifted a few config files around possibly breaking some hard-coded path data.  Here’s the error:

Broken plugin:

Traceback(most recent call last):
File “ankiqt\ui\main.pyc”, line 87 in **init**
File “anki\hooks.pyc”, line 26, in runHook
File “G:\Anki\ankiconfig\plugins\pinyin\anki\main.py”, line 41, in <lambda>
File “G:\Anki\ankiconfig\plugins\pinyin\anki\main.py”, line 82, in initialize
File “G:\Anki\ankiconfig\plugins\pinyin\anki\statsandgraphs.py”, line 202, in install
File “ankiqt\ui\graphs.pyc”, line 7, in <module>
File “anki\graphs.pyc”, line 45, in <module>
File “matplotlib__init__.pyc”, line 709, in <module>
File “matplotlib__init__.pyc”, line 692, in rc_params
File “matplotlib__init__.pyc”, line 240, in wrapper
File “matplotlib__init__.pyc”, line 483, in _get_data_path_cahed
File “matplotlib__init__.pyc”, line 453, in _get_data_path
RuntimeError: Path in environment MATPLOTLIBDATA not a directory

**Comment by marsmars** [comment]
I have the same thing. Removing/reinstalling both Anki and PTK does not really help. Is there any workaround by the time the fix is available?

**Comment by RavinDave** [comment]
Older versions of ANKI had the matplotlibrc config file in a dedicated folder called "matplotlibdata".  That folder's gone (ergo, the runtime error above).  The config file is there, but has shrunk from 13 to 1KB (I assume the info has been distributed to other files, but that's just a guess).

**Comment by batterseapower** [comment]
All the Toolkit is doing is importing ankiqt.ui.graphs. We didn't hard code any paths: the setup of MATPLOTLIBDATA should be done by the following lines in Anki's graph.py:

  # support frozen distribs
  if getattr(sys, "frozen", None):
      os.environ['MATPLOTLIBDATA'] = os.path.join(
          os.path.dirname(sys.argv[0]),
          "matplotlibdata")

Do you get the same error if you click the Graphs button in Anki with the toolkit uninstalled?

**Comment by RavinDave** [comment]
Activating graphs yields:

Traceback(most recent call last):
File "ankiqt\ui\main.pyc", line 1732, in onShowGraph
File “anki\graphs.pyc”, line 45, in
File “matplotlib_init__.pyc”, line 709, in
File “matplotlib_init.pyc”, line 692, in rc_params
File “matplotlib__init.pyc”, line 240, in wrapper
File “matplotlib_init__.pyc”, line 483, in get_data_path_cahed
File “matplotlib_init__.pyc”, line 453, in get_data_path
RuntimeError: Path in environment MATPLOTLIBDATA not a directory

**Comment by batterseapower** [comment]
Just to confirm: that happens even with the Toolkit uninstalled?

If that is so, this is an Anki bug. The Toolkit is just triggering it because it hooks into the graph functionality -- as you can see, you still get the problem if you click the normal Ani "Graphs" button.

If it is an Anki bug, could you report it to Damien? I'm sure he'll figure it out quickly.

**Comment by RavinDave** [comment]
Yes ... that happens with the Toolkit uninstalled.

I'll try to report it later tonight.  Curious no one else seems to have encountered it though.

**Comment by batterseapower** [comment]
Thanks for the work investigating this!
