### ISSUE TITLE
Unicode Bug

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#167]
Here's the long runnning bug which 've been ignoring.., in this case, on the character: 零 (and the english field was not filled but others were)

An error occurred. Please:
Restart Anki. 
Tools > Advanced > Full Database Check. 
If it does not fix the problem, please copy the following
into a bug report:

C:\Program Files\Anki\lib\shared.zip\sqlalchemy\engine\default.py:230: SAWarning: Unicode type received non-unicode bind param value ''

**Comment by batterseapower** [comment]
Hmm. I can't reproduce this on either Windows or OS X with the most recent code. Can you perhaps send me your Pinyin Toolkit.log from a session where you try to create such a card?

**Comment by Nick3C** [comment]
Sent a log as requested.

**Comment by batterseapower** [comment]
OK, I couldn't figure it out from the log, but I've added some code which may fix the bug. Can you try with the latest version from github?

**Comment by Nick3C** [comment]
haven't seen the unicode error since you made this change but have hardly been using Anki. I will keep an eye out and let you know if I see it. On the other hand there are some new bugs (see other thread :) )

**Comment by batterseapower** [comment]
Tentatively closing this as fixed

**Comment by Nick3C** [comment]
yes, I think so.
