### ISSUE TITLE
Cannot install pinyin toolkit due to ImportError

### ISSUE THREAD

**Issue by t3rance** [batterseapower/pinyin-toolkit#175]
I am a n00b. I am running Cruchbang. I have installed Anki. I am trying to install the pinyin-toolkit. Repeated failure. I get this error:

Traceback (most recent call last):
  File "/usr/share/anki/ankiqt/ui/main.py", line 2472, in loadPlugins
    **import**(nopy)
  File "/home/terance/.anki/plugins/Pinyin Toolkit.py", line 29, in 
    import pinyin.anki.main as main
  File "/home/terance/.anki/plugins/pinyin/anki/main.py", line 11, in 
    import pinyin.db.builder
  File "/home/terance/.anki/plugins/pinyin/db/builder.py", line 3, in 
    import cjklib.build
  File "/home/terance/.anki/plugins/pinyin/../pinyin/vendor/cjklib/cjklib/build/**init**.py", line 60, in 
    from sqlalchemy.exc import OperationalError
ImportError: No module named exc

I need help resolving this issue. I dont know where to begin.

**Comment by batterseapower** [comment]
You need to upgrade your installed Python SQLAlchemy package. On some systems, you can do that with "sudo apt-get install python-sqlalchemy".

**Comment by t3rance** [comment]
Thanks for your prompt response.
I tried to sudo apt and i got this error instead:terance@terance-desktop:~$ sudo apt-get install python-sqlalchemy
[sudo] password for terance: 
Reading package lists... Done
Building dependency tree  
Reading state information... Done
python-sqlalchemy is already the newest version.
python-sqlalchemy set to manually installed.
The following packages were automatically installed and are no longer required:
  kakasi-dic kakasi
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 13 not upgraded.
terance@terance-desktop:~$

**Comment by t3rance** [comment]
I tried autoremove.  I still get the original error.

**Comment by batterseapower** [comment]
I suspect that your distribution does not provide SQL Alchemy 0.5 or above. Can you find out which version got installed?

**Comment by batterseapower** [comment]
Closing, no response from submitter.
