### ISSUE TITLE
Call to deprecated function warning

### ISSUE THREAD

**Issue by Attallah** [batterseapower/pinyin-toolkit#176]
This came about after I did quite a bit of editing of a shared deck I had downloaded (Chinese Odyssey), mainly to make the pinyin tone-coloured by spacing it out.  I also replaced the Mandarin Lessons audio with the ChinesePod audio.  Everything seems to function fine and this only started occurring yesterday or the day before, but when I open Anki this warning pops up.  Thanks for the excellent plug-in.  It has helped my Chinese learning immensely:

An error occurred in a plugin. Please contact the plugin author.
Please do not file a bug report with Anki.

/home/nthomas/.anki/plugins/pinyin/db/**init**.py:10: DeprecationWarning: Call to deprecated function getDBConnector.
  database = pinyin.utils.Thunk(lambda: cjklib.dbconnector.DatabaseConnector.getDBConnector({ "url" : sqlalchemy.engine.url.URL("sqlite", database=dbpath) }))

**Comment by batterseapower** [comment]
This should be fixed in v0.6.5.
