### ISSUE TITLE
Tonify Through Shortcut Keys

### ISSUE THREAD

**Issue by batterseapower** [batterseapower/pinyin-toolkit#19]
merge Nick's colorization plugin into PyKit so that it works together.

If tonify is on then we could expand this to add pinyin tone marks too. This is useful when the convertor gets the wrong pinyin (which does happen, after all the dictionary is only a guess, albeit a fairly reliable guess).

If we could make it work in the type-in-answer that would be good too. The current plugin offering has some nasty bugs

**Comment by Nick3C** [comment]
I have done most of this now... even tidied it up a little... just need to work out why it doesn't work now :p

**Comment by Nick3C** [comment]
fixed and now working:
issue closed

side-note, what do you think about the other hotkeys? ctrl-F9 is taken for html editor but we could either use F10,F11, and F12 or leave them blank?

**Comment by batterseapower** [comment]
One thing: whatever hapens we should reduce the number of user colors to match the number of shortcut key we take up. Personally I think 3 user colors is fine (I don't use them anyway)

**Comment by Nick3C** [comment]
oh yes, sorry I forgot about that.

Yes, I think 3 user colors is enough too. We may lose one in the future for the tone sandhi but I still think that is all right... I use them rarely for emphasis etc (basically I use black and light blue to indicate various things).

**Comment by batterseapower** [comment]
My fork has reduced the number of quick access colors to 3 (still need to run build_ui.sh before this will work properly....)

**Comment by Nick3C** [comment]
I have just fixed this again in my fork. Cause was a conflict of import methods (I _thought_ I had fixed it once before :)

**Comment by batterseapower** [comment]
Nice one. Confirmed working for me on OS X
