### ISSUE TITLE
Overhaul erhua handling

### ISSUE THREAD

**Issue by batterseapower** [batterseapower/pinyin-toolkit#2]
I think you may have misunderstood my comment on the neutral tone
and erhua. The idea is that the space should be removed where there is
an erhua, eg nǐ men2r [which is best passed to the lookup engine as
menr2]. This creates a complication when coloring characters. For even
more fun the er character isn't always an erhua, for example "er zi"
where it is a separate sylabul and must not be merged. I didn't mean
anything about the neutral tone [that was just a convenient way to
have the character colorisation not break]. Also erhua are not
necessarily  the end because we may be dealing with a phrase.

**Comment by batterseapower** [comment]
My fork contains improvements to erhua handling. Although it's still not perfect, the infrastructure is in place to make this work better.

What is fixed: sound generation correctly discards the erhua.
What is not fixed: it only works for words, not phrases. That is, it works for the builtin dictionary only. If we want to do this for the output of Google Translate then we will need a Chinese word segmentation algorithm (perhaps using Markov chains?), which is a bit tricky.

**Comment by Nick3C** [comment]
I think that is good enough for now. It is good to catch, but hopefully users running into lots of erhuas will understand the significance and deal with it manually. Let's not worry about it :)

**Comment by Nick3C** [comment]
Another one to note here:
土豆条儿....
the erahua still has a space between the word and the 'r'

**Comment by batterseapower** [comment]
Unfortunately this is expected behaviour because CEDICT:

1) Knows about tudou, and that's the longest match possible, so that becomes one word
2) Knows about tiao, but not tiaor, so we get another word there
3) Knows about er, so thats another word

And an er5 doesn't have its space eliminated if it stands by itself in its own word.

Note that 炸土豆条儿 (which IS in the dictionary) gets the r unspaced as you would expect.

**Comment by Nick3C** [comment]
isn't the solution to just find an " r" and replace it with and "r" ?
when used in a word the "儿" is always er, eg 儿子

If it is meant to be an "er" and is an " r" then this is wrong anyway, so we might as well be right most of the time instead of wrong all of the time (also erhuas are much more common than non-dictionary "er"s)

here's another one: 书皮儿... 

the other way to solve the problem is just to fill the dictionary with them all, hahaha :)

**Comment by batterseapower** [comment]
There seems to be lots of examples where r5 occurs by itself... check CEDICt for e.g. 刺儿李 (gooseberry).

**Comment by Nick3C** [comment]
Can you give me any other examples? I don't know of any words that have an 儿 that is read r  and it is not an 儿化, largely because an erhua is not really a word so the "r" is simlpy a way of representing the slur in written Chinese. If is is an "r" then it is an erhua by definition :)

**Comment by Nick3C** [comment]
sorry, lost the start of my message...

I was explaining that that is an erhua. Look at the online interface, it is written cir (meaning thorny, i.e. thorny plum). It can't mean -thorn-child-plum.

The whole concept of "a word" is rather foggy in Chinese, this is one example. Wenlin confirms that this is cir. Sometimes erhua are compulsory in a word such as here (changing the meaning from thorn or price, to something more like thorny. Generally they are optional.

However, the definition of an erhua is that it is that "r" sound like a Somerset accent. Where it appears as "er" that is the word er, not an erhua. Thus all "r"s are erhua.

**Comment by Nick3C** [comment]
http://en.wikipedia.org/wiki/Erhua

**Comment by Nick3C** [comment]
as a fun side-note that lets you listen to cute little kids erhua-ing, see here: http://www.bjshengr.com/bjs/2008/01/does-the-beijing-r-mean-anything/ :)

**Comment by Nick3C** [comment]
I've just had a look at MDBG... everything I can see with r5 is an erhua. really :)

**Comment by batterseapower** [comment]
OK, if that really is the case it makes erhua handling a lot simpler :)

**Comment by batterseapower** [comment]
Done in my fork.

I think you eventually got the correct spec through my thick skull :-)

**Comment by Nick3C** [comment]
lol, you've been very nice about my thick programming-skull so fair's fair :)
