### ISSUE TITLE
Hanzi Masking in Translation Field

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#29]
if the phrase in expression appears in translation it should be replaced with ㊥ or some other text such as [~] to show the position of the character in the expression fiel (otherwise you see the chinese and pinyin when testing so 'cheat') it is fine to keep it as ㊥ because then it there is an example you haven't broken it. It may appear in blocks of text o it is better to keep in some.

**Comment by batterseapower** [comment]
Nick has implemented tihs. I also changed it so that it masks tone information for the character as well as the character itself.

**Comment by Nick3C** [comment]
ah, nice one.

I did think that we might try hiding any character in the expression field. Still not sure if this is a good idea. let's try it for a while before making any decision.
