### ISSUE TITLE
Add option to use a different color for the dictionary line-index reference

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#33]
I'll add a few lines to do this. Pretty simple but will make it easier to distinguish entry from text

**Comment by batterseapower** [comment]
What is the line index reference? You mean for the meaning numbering?

**Comment by Nick3C** [comment]
yes, like (1), (2), (3) - it looks better with a different color to distinguish it from the main entry.

**Comment by Nick3C** [comment]
I implimented draft code for the color change (but not to pass the option), as usual it doesn't quire work :$

**Comment by Nick3C** [comment]
fixed and implemented. Uses config.db so we just need to add it to preferences now. Default color is grey
