### ISSUE TITLE
Audio Pack randomisation

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#38]
I now have 4 decent and working audio packs in place. 3 female, one male. It occurs to me that it would be nice to be able to randomise which one is used. How exactly does choosing a pack work at present? You said it choses the best pack, but what if several are equally good?

**Comment by batterseapower** [comment]
If several are equally good then it just picks the alphabetically first one. Now you mention it perhaps randomisation would be a better idea.

**Comment by batterseapower** [comment]
Nondeterministically choose from best of several audio packs. Closed by 99b2a427cd93d6ef728d180c0a1f3e883b1b5c47
