### ISSUE TITLE
Change Field Config to Have only one User-customizable field

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#40]
There is no need for us to allow the user to customise every field for every data type. all we need is one field. This would also mean we could remove the entries from the config.db and make it easier to update and maintain, etc.

There should be a single user-customisable field for each entry which gets priority over the default list.

**Comment by batterseapower** [comment]
I don't think this is true, because the preferences are not per-deck, they are per-user. What if I have different field names in each deck?

I think the current solution is the right one.

**Comment by Nick3C** [comment]
ok
