### ISSUE TITLE
Force Unimportant Auto-generated Fields to be Small

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#41]
Pinyin Toolkit requires models have a lot of fields. This can be irritating for a user as it reduces the visable space for the main fields (expression, pinyin, meaning). The solution is to resize the fields. I do this already in my local Anki but we should ship the feature with Pinyin Toolkit for the following fields:
- MW
- audio
- links
- PoS [not yet implimented]

Code to do this is below:

Use codedef FieldMW(widget, field):
    if field.name == "MW":
        widget.setFixedHeight(30)

addHook("makeField", FieldMW)

**Comment by Nick3C** [comment]
This is sufficiently important that we can't release 0.06 without it.

On my main deck I have 9 fields, even with shrinking on 4 of them there is not that much space. I presume that without the field shrinking it is starting to become very ugly because of the lack of space for the main fields

I could probably manage this one...

**Comment by batterseapower** [comment]
Do we really want to do this for measure word? I can see that we might want to for audio + links, because they are not really human-editable, but the user might want to change MW.

**Comment by Nick3C** [comment]
In my view it should be done for MWs too. I used to edit them manually (pre-plugin) it was a pain and I rarely did it (and this was when I was manually generating color :). I have had a single line MW since before PYTK auto-generated data.

For the most part MW is not populated and just wastes space (non-nouns, non-cedict). Also MW is almost always only one-line even when it is present.

There is a compromise. How valuable is that lost space? In my view it is more valuable than the rare benefits of editing. If anyone complains we can point them at the line number they can delete to turn it off.

**Comment by batterseapower** [comment]
Add field-shrinking hook. Closed by 4ed85bf3e6be1728a1172efa08eb921f91fb7b39
