### ISSUE TITLE
Decide what to do about user colors

### ISSUE THREAD

**Issue by batterseapower** [batterseapower/pinyin-toolkit#43]
Either we should reduce the number of user colors to 3 (to match the available shortcut keys) or use up Ctrl+F10-12 so we have 6 user colors.

I don't mind which option we choose, but the change needs to be maed to the defaults (in config.py) and the preferences dialog.

**Comment by Nick3C** [comment]
Is it possible for us to move the html shortcut to ctrl+f12? then we could use ctrl+f6 to control f11 for this

**Comment by batterseapower** [comment]
It is /possible/ but it would be sort of a hack and it might make the plugin a bit vulnerable to changes in Anki.

**Comment by Nick3C** [comment]
plan for now: just use 3 user colors. Consider expanding this in future if Anki shortcut is changed. Plan accordingly in development.
