### ISSUE TITLE
Bug with plain numbering

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#44]
selecting plain numbering in editor cause an exception due to colorindex. think I broke this yesterday.

**Comment by Nick3C** [comment]
149, in generatemeanings
    return self.config.formatmeanings(meanings,lineindexcolor)
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\config.py", line 210, in formatmeanings
    meanings = [meaningnumber(n) + " " + meaning for n, meaning in enumerate(meanings)]
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\config.py", line 202, in meaningnumber
    if (colorindexs):
NameError: global name 'colorindexs' is not defined

**Comment by batterseapower** [comment]
I can't find this code in my fork currently. Are you sure you have updated recently?

**Comment by batterseapower** [comment]
I've pulled from your branch and resolved the conflicts, and the code still doesn't exist. It's likely that the bug only exists in your fork - try a pull again?

**Comment by batterseapower** [comment]
I think we decided that this code doesn't exist, so I'm closing the issue.

**Comment by Nick3C** [comment]
sorry about that, chances are (because of my hard-link situation) that I forgot to commit changes and then overwrote the anki plugins dir with the git project dir.
