### ISSUE TITLE
Automatic Tonification & Colorisation in Pinyin Field onfocuslost

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#45]
For situations where the user manually corrects the pinyin returned from the dictionary the pinyin should be automatically tonified and colorised (depending on settings).

Howver, no change should be made if it is not in the pinyin format (eg already tonified). Dealing with color may be tricky. May need to trip html and start again (but that would require conversion from toned to toneless pinyin (which is not simple)

**Comment by batterseapower** [comment]
Implemented in head. Try it out and see what you think. There is a new menu option for doing it to all your cards at once as well.

**Comment by Nick3C** [comment]
I like it, but don't have the courage to run it on the whole of my main deck yet :)

I will play with it some more and see how it goes.

By the way, we really go need to move those menus to new places, the user who complained about it was right. We need preferences to go next to Anki's preferences and the advanced fill features to slot into advanced.

Did you see the note about "tools" being disabled in the deck browser (until a deck is loaded)

**Comment by batterseapower** [comment]
Yeah, we should definitely close those tickets before the next release - I haven't forgotten them! The "tools" menu is actually not disabled when you are viewing the deck browesr on a Mac, so this hasn't been a problem for me, but it needs to be fixed for Windows users.

**Comment by Nick3C** [comment]
note that is a slight issue with pinyin generated by the basic pinyin plugin in the form {a, b, c} which is broken. Normally you could still choose which one you wanted even at a later state. I don't think it's really worth fixing though. It's not a major issue.

hopefully this isn't a repeat (cant remember if i posted this elsewhere). But this pinyin conversion should really be done during the onfocus change away from expression (if reading can't be over-written because the field has contents).

**Comment by Nick3C** [comment]
actually this should happen in every field. if the user wants colored and tonified pinyin in meaning, for example, it should happen automatically

**Comment by batterseapower** [comment]
So you're saying that if we colorise {a, b, c} the double-click thing no longer works? That's probably best fixed by changing the relevant code Anki if it is the case.

RE colorisation in every field: yes, I was thinking that. It would be particularly handy in meaning, but also in other fields  (e.g. I have a "grammar notes" field it is useful to put pinyin in)
