### ISSUE TITLE
Audio Generation  for MWs

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#49]
Add audio generation so that MWs also have audio in their field:
      [MW1 data][MW2 data][MW3 data]
      [MW1 audio][MW2 audio][MW3 audio]

probably needs an option (in case people only want to display it on other cards and not test directly (although this is a bad idea, see minimum information principle).

**Comment by batterseapower** [comment]
Shouldn't we have an MW Audio field just like we have an Audio field now?

**Comment by Nick3C** [comment]
It can be done, of course, but the question is whether it is a good idea. It has the advantges of:
1) more flexibility in MW placement (placing MW on a card without it's audio)
2) neater audio generation

But the disadvantages of:
1) adding another field to the add list (we have many already)
2) swelling the database size with a second MW field (when both are rarely used)
3) is probably going to be used every time the MW is used (assuming people obey the minimum information principle which says they shouldn't have the measure word on their main cards)

I know that I would never separate them, and I tend to feel that I wouldn't really want a user to seperate them wither (because the only function I see for doing so is something that I disagree with in principle).

About the only strong argument in support of it is that it keeps the fields neater (which is why I wanted the audio to all be placed below the MWs). If this is convincing then we cold have separate fields we could shrink the MW field size to like 1 pixel in the edit window so that it is effectively invisible.

We don't have to decide on this right now. It can certainly wait until a later release

**Comment by Nick3C** [comment]
I have revised my view on the above. I think we had better follow your idea of a separate field for MW audio. It let's us do something a little more exciting:
[random quantity][MW][noun]

where random quantity is 1 to 9 or 几.
If there is more than 1 MW then we could do this for each of them.

**Comment by batterseapower** [comment]
Add measure word audio generation. Closed by cec1b22f2a86b0da174bfd4c06c546b4ec5164b9

**Comment by batterseapower** [comment]
Cool idea. Implemented in my branch.

**Comment by Nick3C** [comment]
Two very minor issues:
I didn't look at the code right away and tried "MWAudio" as my field name. How about looking first for those fields spaced, and secondly without a space.

Was there a reason you chose to exclude 几 (meaning a few) in the numbers by the way? I think it has universal applicability.

Secondly, I don't see why we can't look for [MW candadate] [audio field candidate]. Which would make it a bit neater and easier to update.

**Comment by Nick3C** [comment]
ok there's a bug, or quasi-bug... different audio packs can be used for the audio and mwaudio which produces a strange effect. might be a bit difficult ot fix and not worth it.

**Comment by Nick3C** [comment]
ahhhh, sorry a big bug now... the generation routine is using the dictionary for audio not the field. It needs to scan the MW field for characters and use those (otherwise no audio is generated for manually added characters).

I must say though, where it works, it is very cute indeed.

**Comment by batterseapower** [comment]
I just forgot ji3 - I've added it now. I've also changed the field naming to just use the names for mw and audio fields and munge them together. The reason I didn't do this before is that it makes the code a bit uglier.

MW audio is only being generated in expression onfocuslost. We could add a feature like we have for the audio field currently where you can type stuff into the MW Audio field and get it reformatted automatically, but thats another feature. An alternative interface would be the one you suggest - an onfocuslost hook for the MW field.

I'm raising a new ticket for that request.
