### ISSUE TITLE
Tone sandhi support for 3rd tone (sound and color)

### ISSUE THREAD

**Issue by batterseapower** [batterseapower/pinyin-toolkit#5]
Tone Sandhi is where a (3,3) -> (2,3) and a (3,3,3) changes to either (3,2,3) or (2,2,3).

The former situation can be managed, the latter cannot (because it is too complicated and is context-specific).

The sound generation is quite important (because otherwise the audio is actually wrong). The color is less important but both can be dealt with together.

**Comment by batterseapower** [comment]
Note: Nick tested this using a yellow color for pinyin (to show change to 2nd tone) didn't work and interfered with memory; perhaps could try again with a (very slightly) lighter green color but maybe better justnot to do this.

**Comment by Nick3C** [comment]
I plan to trial usage with a lighter colour. To be honest a different color makes reading colored character much easier (you don't need to think about it). The issue was:
- 2nd tone is orange
- I used light yellow for the sandhi (to show it had become 2nd tone)
- this worked for reading but I tended to remember it as a 2nd tone
- with a green I suspect it will be better (but as I have to trial it for a couple of months this is certainly not urgent)

**Comment by Nick3C** [comment]
I have decided that #66CC66 is a good choice because it looks like the normal green, but a touch faded. It should be alright to remember as "green" but hopefully the difference will be enough to prompt memory of the tone-change.

**Comment by Nick3C** [comment]
I have just realised that this has become a much bigger priority because the code now checksums the audio hides the [sound:ni3.ogg][sound:hao3.ogg]. This means that it is very difficult to change the tone on the first word from 3 to 2 (and it means that we are generating manifestly incorrect audio)...

**Comment by batterseapower** [comment]
Some questions:
- Should you apply sandi between words as well as within them? (I'm think the answer is yes)
- If so, what do you do with a set of tones like 3333? Does that become 3232?
- Certainly an ambiguity problem with 333333. Can become 232323 or e.g. 323323
- Which of 333 -> 323/223 is most frequent? Since 333 is always wrong we may as well change it to one of the possibilities.

This is really easy to implement, I just need to understand the rules :-)

**Comment by Nick3C** [comment]
Your questions:
Q1 - yes, it is the tones being in a row that matters, not the fact they are in different words (for the simple case of (3,3) anyway, see below for (2,3))

Q2 - this is the whole problem, not necessarily. Sometime (3,3,3,3) will become (2,3,2,3) but sometimes it will become (3,2,2,3) and sometimes (2,2,3,3).

Q3 - this can become many things :p

Q4 - the most frequent is probably: to assume each unit of (3,3) changes to (2,3) with odd numbers being left with an extra 2 at the start: (3,3,3,3,3,3)[6] -> (2,3,2,3,2,3) and (3,3,3,3,3)[5] -> (2,2,3,2,3)

Perhaps we could do number 4 for now but look at something more sophisticated in the future. I will have a go at settings out the context rules.... I think it is something like this (no guarantees though!). Square brackets mean a word:
- simple rule: a mono-syllabic word loses it's third tone if followed by another mon-syllabic word
- a monosyllabic word in front of a multi-syllabic word keeps its third tone, the multi-syllabic word changes to 2^x,3
- monosyllabic word after a multi-syllabic word keeps its third tone but the multi-syllabic words lose all of their third tones
- multisylabic words not followed by monosyllabic words convert all third tones except the last into second tones.

This seems to be the general position (from my self-probing on the rules). However, I am fairly sure that these vary depending on what the words actually are; if there is a space between them as a result of meaning etc.

If you want to implement the above tone rules they are better than a simple (2,3) in all cases but I am sure that whatever we do someone will tell us we are wrong.

**Comment by batterseapower** [comment]
Harder than I thought :-)

**Comment by Nick3C** [comment]
Let's implement simple (3,3) -> (2,3) support and look at fixing this properly in 0.06

**Comment by batterseapower** [comment]
Nick, I have a prototype of this going now. It tries to deal with all 3rd tone sandhi, including the 333 situation (though is probably partly broken and needs some tweaks). One question though before I commit it: should this be applied to generated readings as well?

**Comment by Nick3C** [comment]
ok great. hahaha, let's see if it does work or not, did you see jsv joking about it in the forum? I am not convinced convinced that it can be coded for, but I'll give it a go.

Not the reading remains as 3 when written, it only changes when spoken. However... this is where we would color using the slightly lighter share of green. I suggested one in the code. Can we try that for a few days and see how it looks?

**Comment by batterseapower** [comment]
I'm sure the logic isn't perfect. It definetly needs stress testing by someone who knows more than I do about its nuances. It might satisfy jsv though :-)

So to summarise what you are expecting is that:
- Colored chars get a lighter shade if the tone is subject to sandhi
- Likewise with the Reading, but tone marks DO NOT change
- Likewise with any characters appearing in the Meaning, but again tone marks DO NOT change
- Audio uses the sandhi to select different sounds, so hen3hao3 maps to hen2.ogg hao3.ogg

**Comment by Nick3C** [comment]
that is all right. wow, you have had a busy-evening haven't you :)

**Comment by batterseapower** [comment]
As you may have noticed, I'm trying to get this new release ready :-)

Haven't yet implemented the behaviour above - I need to overhaul the handling of tones internally generally so it's a bit more extensible (we need two kinds of tone info - spoken and written), so I'll try and do this tomorrow.

**Comment by Nick3C** [comment]
Yup, that sounds right.

**Comment by batterseapower** [comment]
Support 3rd-tone sandhi. Closed by 479ed26a568dd375f4a687ccd6ac51fc611a8ac0
