### ISSUE TITLE
Hanzi found in translation lookup should be black not uncolored

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#51]
This makes a difference to users who have their meaning fields coloured in colours other than black (I think there are many of these because it makes it easier to quickly distinguish a field when glancing at the card). Easy fix.

**Comment by batterseapower** [comment]
Not sure I understand. Can you give an example?

**Comment by Nick3C** [comment]
Anki has it's own provision for colouring fields (configured in the Settings -> Fonts & Colours window).
For example my English fields are colour-coded with a light blue colour.
Any html in a field over-writes the Anki font settings so that colour is displayed instead (eg our coloured pinyin).

However, it is not a very good idea to colour hanzi (as we are using their colour to represent tones).
They are not coloured in reading because we have put the pinyin right next to them, so the intention is for them to come back black.
However, they actually come back colourless and so Anki colours them light blue (which is not what we want).

Beca

**Comment by batterseapower** [comment]
Why would Hanzi appear in the reading? Do you mean the "meaning"? Almost all hanzi appearing in that field should be colored with their tone information already.

**Comment by Nick3C** [comment]
sorry, I meant meaning.

Really? Then I think we have a bug. Try this: 咔嚓 which has 喀嚓 in it (which is also in the dictionary). The pinyin is coloured but the hanzi is not. I presumed this was deliberate.

**Comment by batterseapower** [comment]
OK. My fork contains code that colorises the characters in addition to the pinyin for examples like the one you point out. This addresses the immediate problem.

However, there is still no provision for making characters that appear in a field explicitly black - this requires a bit more work to do well (although a hack to flatten would get 90% of the cases). One hacky solution would be to make a change to the colorizer so that hanzi occuring within Text (i.e. Hanzi without tone information) are wrapped in black tags. Not very nice though!

**Comment by Nick3C** [comment]
can't we just run a lookup function on it (or would it be slow?). the hack is better than nothing if it's not easy to colourise.

**Comment by batterseapower** [comment]
We can and do run a lookup. The one problem is in situations where things in the dictionary have a number of pinyin that doesn't match their character count - my code has to bail out in that situation, as it doesn't know how the tones match up.

This will also be a problem for characters that do not appear in the dictionary at all that occur in the meaning w/out pinyin information (rare?) and characters coming back from Google Translate.

I think the situations where this is going to happen are sufficiently rare that we shouldn't worry about it.

**Comment by Nick3C** [comment]
yup, black is a good option. it simply isn't worth writing code to deal with this very rare situation.
