### ISSUE TITLE
Create a Pinyin Toolkit Blank Deck and add it to the deck browser

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#52]
Do this, on the basis that users shouldn't have to implement so many changes to their decks at once when we can supply a sample for them that they can download (or at worst they can copy and paste the fields).

In fact I would probably suggest two decks: Simple and Advanced (one with more complex models and one with much simpler models).

**Comment by batterseapower** [comment]
Yes! You may have noticed that I added a link from the "Get it" website page (http://batterseapower.github.com/pinyin-toolkit/getit.html) to a "demo deck" which I suggested users install after the Toolkit, but I haven't actually got around to creating it yet :-)

**Comment by Nick3C** [comment]
lol, I hadn't noticed. At least we continue to think along similar lines

**Comment by batterseapower** [comment]
I have a demo deck created as part of the new site. See http://batterseapower.github.com/pinyin-toolkit/files/pytk-demo-deck-0.9.9.8.1-v1.zip

Closing the issue as fixed.

**Comment by Nick3C** [comment]
Hmmm, ok. There are quite a lot of ways that this deck can be made better by altering the card templates, model order, and even fonts so that it gives a better user experience. Other things, such as putting the MW on the cards is just a bad idea, you won't learn them (because of the minimum information principle and they will get in the way and distract you from the main vocab It will only get in the way [see http://www.supermemo.com/articles/20rules.htm#minimum information principle]. Finally the deck doesn't make full use of the power of having these things auto-generated for you.

I really don't want to put up so-so show decks because it lets down the way the final product looks. I know I said I would look at this and I honestly will, I'm just rather busy at the moment because I'm trying to catch up with my dissertation (due in 6 weeks and well behind schedule) That's why I've cut back on the code-editing too. :)

**Comment by batterseapower** [comment]
I agree the deck is kind of rubbish for actual learning, but I slapped everything into the template because it looks really pretty as a demo :-)

Will gladly replace it with a better deck constructed with some actual care an attention when that arrives.

**Comment by Nick3C** [comment]
done. uploaded to website and included in a sample directory in the plugin.

I will upload them to the main anki hosting (so they can be downloading from within Anki) after we go live with the release.

**Comment by Nick3C** [comment]
changed my mind... no harm to upload them now as a taster... it's done... what do you think?

**Comment by batterseapower** [comment]
Decks look good to me - nice work.
