### ISSUE TITLE
Manual Generation of Index Lines

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#60]
auto replace (1), (2), (3), etc onfocus change from any field to another

**Comment by batterseapower** [comment]
You mean, replace them with the circled variants? Similar to what you want to do with automatic colorisation of pinyin?

**Comment by Nick3C** [comment]
yup. should be straightforward too.

**Comment by Nick3C** [comment]
the reason is that... editing the entries returned from MDBG is currently a bit of a pain (because you have to copy and paste into the existing 1,2,3). I use a text-macro to do it, but that's hardly the best approach.

**Comment by batterseapower** [comment]
Should be easy to fix now we have better pinyin parsing. Moving the priority up.

**Comment by batterseapower** [comment]
Er wait, that has nothing to do with pinyin parsing. However, we do now have the infrastructure to add onfocus hooks to arbitrary fieds.

**Comment by batterseapower** [comment]
Implemented. Works very nicely.

**Comment by Nick3C** [comment]
that's very nice
