### ISSUE TITLE
Escape Character Bug (from google translate)

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#62]
We need to trim escape characters when returning from google translate (best do it afterwards (so all dictionaries can benefit when we add them in the future).

eg query:
“三农”问题是指农业、农村、农民这三个问题
\"Three Rural Issues\" refers to agriculture, rural areas, farmers of these three issues
[Google Translate]

**Comment by batterseapower** [comment]
Yeah, We should deal with definitions returned by Google at the same time (try searching for a single character like hao3)

**Comment by batterseapower** [comment]
Both issues are fixed in my fork.
