### ISSUE TITLE
Implement Full Support For Mandarin Model (as per Damien's request)

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#66]
As per Damien's email:

---

The next version of Anki will remove all language-specific features in
favour of plugins. The Mandarin plugin does a much better job of
generating readings. Likewise, I'm looking at moving the Japanese
reading support from Kakasi to a better reading generator with a
larger dictionary. These larger dictionaries result in better
performance but they increase the size of the Anki download, and it's
not really fair to users who don't study Chinese or Japanese. New
users will be able to go to File>Download>Shared Plugin and search for
'japanese support', 'mandarin support', etc - and of course the
documentation will need to be updated for this.
- Please add Mandarin to the standard models in your plugin, like this:

import anki.stdmodels
# Mandarin
###### 

def MandarinModel():
   m = Model(_("Mandarin"))
   f = FieldModel(u'Expression')
   f.quizFontSize = 72
   m.addFieldModel(f)
   m.addFieldModel(FieldModel(u'Meaning', False, False))
   m.addFieldModel(FieldModel(u'Reading', False, False))
   m.addCardModel(CardModel(u"Recognition",
                            u"%(Expression)s",
                            u"%(Reading)s<br>%(Meaning)s"))
   m.addCardModel(CardModel(u"Recall",
                            u"%(Meaning)s",
                            u"%(Expression)s<br>%(Reading)s",
                            active=False))
   m.tags = u"Mandarin"
   return m

anki.stdmodels.models['Mandarin'] = MandarinModel
###### 

If 0.05 is still a-ways off, it would be very nice if you could do
this to the current version in the shared plugins area.

**Comment by batterseapower** [comment]
This is a big opportunity for the Pinyin Toolkit. If users have to download a plugin to get any Chinese support at all then we're in an excellent position to become the defacto choice for all Anki users. Pretty cool!

**Comment by Nick3C** [comment]
Indeed :)

**Comment by batterseapower** [comment]
I've added this code to the plugin initialisation.
