### ISSUE TITLE
Add A Pinyin Toolkit Preferences Tab in Anki's Preferences Window

### ISSUE THREAD

**Issue by batterseapower** [batterseapower/pinyin-toolkit#7]
Should also have a proper story about saving the preferences to disk

**Comment by batterseapower** [comment]
I've added this now. Looks nice, but we don't yet allow configuration of:
- Audio file extension list
- User colors
- Candidate field names
- Deck tag
- index-line number color [added by Nick]
- link-bar settings [added by Nick]

**Comment by Nick3C** [comment]
Audio file extension list
I don't see any need to allow configuration for this. Why can just specify all the files anki can support. Especially with audio packs.

User colors
Yes, need this in the future.

Candidate field names
We only need to allow one candidate field to be added (at the start of the list), the rest of the list can be left intact. If the user specifies something silly then the correct fields will still be found because the others are on the list.

Deck tag
???

**Comment by batterseapower** [comment]
Agreed RE audio file extensions.

User colors is easy to do, not sure where in the dialog it should go though. At the moment it's a bit of a non-issue because the color shortcut keys don't work!

Deck tag: e.g. currently the deck tag is "Mandarin", and that is baked in. Is it better to allow users to specify the tag they want to use?

**Comment by Nick3C** [comment]
I think it probably isn't necessary to allow customization of the tag. All manadarin tags use this tag and you can have multiple tags per deck. Let's leave it out and see if anyone complains.

**Comment by batterseapower** [comment]
working now.  It looks GREAT. A few suggestions:
- Order of fields in preview should match the current deck. If they are missing then should display "not present"
- in the audio tab an option for "Enable Text-to-speech"
- text on the tone color buttons is not colored
- text on the tone buttons is displayed in a font that doesn't support pinyin so 3rd tone looks messed up (on my system)
- Seems MW generation and audio are not using the english dictionary at the moment because they don't work in french (and MW doesn't work in german)
- the window is a bit massive :) Could we look at having a pop-open preview on the right hand side so that it matches Anki's font dialogue?
- Need to reduce the massive size of audio files dialogue. It is only likely to be 3 or so sound sets, right?

**Comment by Nick3C** [comment]
also need to add the index-line color now that I have implimented it.

Also, the link-bar that I had added needs to be added. The easiest way to do this is probably to have a text-edit box that lets the user specify their own html for it. What do you think?

**Comment by batterseapower** [comment]
I know that I broke the prefs dialog in the last commit. It will be fixed soonish, I hope... I can't run the build_ui.sh script on this laptop :(

**Comment by batterseapower** [comment]
Need option for:
- Hanzi masking
- Meaning numbering color
- Link box (allow specification of name and URL with embedded {searchTerms} I think). Also provide a way to turn this off, I guess.

**Comment by batterseapower** [comment]
Prefs dialog works again now. I've tried to fix some issues:
- Should be a bit smaller now
- Have option for text to speech
- Can configure user colors

**Comment by Nick3C** [comment]
Looks Good. I like the changes to the preview that fixes the overlap bug. I still think it would be good to follow two of the conventions of the Anki font window though (having the preview on the right-hand side, and making it possible to turn on and off [faster])

I am not too clear on how the windows-design work. Would it be possible to reorder it t match the model, it's a bit funny to have all the fields out of order. Also, given that we know the size of the data, it would be good to use half-height fields for everything except meaning (to make the window a bit less monstrously huge :)

Can we color the buttons in preference with the current color?

I still get an exception on trying to open audio dir
Traceback (most recent call last):
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\forms\preferencescontroller.py", line 133, in 
    self.view.connect(self.view.controls.openAudioPackDirectoryButton, SIGNAL("clicked()"), lambda: self.openAudioPackDirectory())
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\forms\preferencescontroller.py", line 165, in openAudioPackDirectory
    utils.openFolder(self.mediamanager.mediadir())
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\forms\utils.py", line 14, in openFolder
    subprocess.Popen("explorer", path.encode(sys.getfilesystemencoding()))
  File "subprocess.pyc", line 544, in **init**
TypeError: bufsize must be an integer:

**Comment by batterseapower** [comment]
Regarding the field order: currently it's not based on the current deck at all. I can change this but since it's just cosmetic it's been kind of a low priority.

The buttons _should_ be colored with the current color - I don't really know why that isn't working on Windows. Likewise the 3rd tone issue you reported before.

I'll have another look at the subprocess thing - I can't run the code since I'm not testing on Windows, but I copied it from Anki so assumed it would work :-)

**Comment by Nick3C** [comment]
ok, not a high priority... I just don't like the current order (because it doesn't make much sense :)

Expression should be at the top because it is the core field (from which everything else is generated. Then it makes sense to put color second (because they are the same), then pinyin (because it represents the Chinese) then MWs (because it is usualyl full and on similar lines), then audio (because it is boring) and finally POS and links (because they are boring and won't be interesting to look at)

I seem to recall some bug with the QT toolkit that may be preventing this from working properly. Damien used a hack to color the background in the field-editor window. I had thought the bug was limited to backgrounds but it could also affect the text color.

A solution might be to have a small label and then use the background hack in faceditor.py for a button to show the current color.

**Comment by batterseapower** [comment]
OK. I've fixed the issue with the button colors not working on windows, and I've changed the example characters to "u"s from "a"s because u3 looks slightly less horrible than a3 on Windows. I don't really know why the third tone is rendering so badly though - perhaps there are no bold variants for this diacritic in the default font?

**Comment by batterseapower** [comment]
To summarize what remains to be done at this point:
- Candidate field names (hard)
- Index-line (meaning) number color
- Field ordering + naming + absence indication in the live preview. Defer this?
- Hanzi masking

Deferred:
- Link-bar settings
- Audio extensions?
- Deck tag?
- Reduce window size even more?

**Comment by batterseapower** [comment]
Hanzi masking and meaning numbering are done in my fork. What remains is:
- Candidate field names (hard)
- Field ordering + naming + absence indication in the live preview. Defer this?

**Comment by Nick3C** [comment]
Changes:
1) index-line on or off
2) add color to hanzi masking (same as index-line, whatever that is)
3) defer: field ordering, naming, absence
- no need to ever do audio extensions. IFpeople want others they can tell us and we'll add them. I don't know what anki supports but can't be more than 10 or so.
- deck tag isn't that necessary, it will cause problems with other plugins. leave it if/until it is demanded for good reasons
- window size down would be good; halve the size of fields that have little in them in the eg?

**Comment by Nick3C** [comment]
Max. I think these two things can be deferred. I want to get the release out sharpish :)

I have been through the documentation to get it to a sensible state so I am ready for that to go out. I've also uploaded better sample decks (any comments?)

Unless you have any objections I think we can release 0.05 as soon as those last few preferences are zapped (and references to the audio files are updated to be Mandarin-Lessons.com instead of Mandarin sounds). Today maybe? Tomorrow?

To release I will upload the new version (replacing the old one so we keep the download count) and then spam the forum.

**Comment by Nick3C** [comment]
I was just admiring the new sandhi tone colour, unfortunately I am also getting an exciting preferences error at the moment: :-)

  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\forms\preferencescontroller.py", line 124, in setUpQuickAccessColors
    if pinyin.utils.isosx():
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\utils.py", line 370, in isosx
    return os.uname()[0].lower() == "darwin"
AttributeError: 'module' object has no attribute 'uname'

**Comment by batterseapower** [comment]
Try to create a new ticket for new bugs, this one is long enough as it is :-)

Anyway, I've fixed the uname issue - I missed the bit in the docs that said that it was only available on Unix-like OSes.

Regarding preferences, which ones do you currently think are essential for the release?

**Comment by Nick3C** [comment]
the only thing I think needs doing is to color the masing character with the same clor as the line-index color (they are basically serving the same purpose so no problem to have the same colour).

Other than that I think we are good to go. I was waiting for you :)

I vote to launch tonight =)

**Comment by Nick3C** [comment]
the only thing that _may_ be worth waiting for is release of anki 0.9.9.9.2 (which will pass multiple audio files to mplayer at once). It will make Pinyin Toolkit seem much better...

**Comment by batterseapower** [comment]
Just implemented the colorisation of masks. It's in my fork.

RE a launch: agreed. Seems like a good breaking point to me.

**Comment by batterseapower** [comment]
This ticket has got confusing and long. I'm closing it in favour the broken-out features in #76, #77 and #78.

**Comment by Nick3C** [comment]
Ok then, if we are agreed then when Damien launches that release (assuming it doesn't break the plugin) then I'll do the launch. I expect it before Monday.

**Comment by Nick3C** [comment]
he says he'll have it out any time this evening...

**Comment by Nick3C** [comment]
ok, new snapshot breaks plugin

http://groups.google.com/group/ankisrs/browse_thread/thread/51b647ae23d314e8/43256ae9bf76d8d7#43256ae9bf76d8d7

**Comment by batterseapower** [comment]
I already noticed this and I'm fixing it.

BTW to fix hanzistats copy the isHanzi function from PyTK into it and change its use of isKanji into isHanzi. Lucky I already duplicated that code into PyTK before he deleted it :-)
