### ISSUE TITLE
Progress bar for dictionary loading

### ISSUE THREAD

**Issue by batterseapower** [batterseapower/pinyin-toolkit#70]
Rainers suggestion. We can either do this or move to a SQL backend, which wouldn't require us to load the dictionary at all.

**Comment by Nick3C** [comment]
another user suggestion:

> Just a small detail. It might be nice to have a small progress bar 
> while the dictionary gets loaded (like the one when opening the 
> graphs' window). Now it feels like Anki freezes after hitting tab the 
> first time.

**Comment by batterseapower** [comment]
No longer relevant because we use cjklib.
