### ISSUE TITLE
Bug with English Letters in Expression field

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#71]
I have another bug :p

eg "U盘" meaning (USB drive, literally: U-disk) or "C盘" (meaning C drive). Then, because 盘 has a dictionary entry this will be returned. The expected behaviour is to pass the query to google translate because C盘 is clearly different to 盘.

**Comment by batterseapower** [comment]
OK, but this does mean that stuff like:

鼓聲 (junk!!)

Will also return no meanings, which is kind of irritating :-)

**Comment by batterseapower** [comment]
Don't return meanings for things containing unrecognised tokens. Closed by db5f26c9648d704b1abc5147bdb434f45be39b95

**Comment by Nick3C** [comment]
ah well, such is life. This solution works well I think.

**Comment by Nick3C** [comment]
yikes...
can not do this for punctuation though. _that_ doesn't make sense...
eg 你好! does a google search instead of returning the dictionary entry

**Comment by batterseapower** [comment]
:-) I knew this would have unintended consequences!

Fixed in my fork.

**Comment by Nick3C** [comment]
luckily for us I compulsively type in long strings of similar phrases after these sort of changes to see what differences occur :p
