### ISSUE TITLE
Sound FIle Renaming for Attribution Under License

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#72]
Max, just to let you know. We need to give the audio files their proper name before we release.

We have taken to calling them "Mandarin Sounds" but they are actually from "www.chinese-lessons.com" I propose we rename them as "Chinese-Lessons.com Mandarin Sounds", otherwise I feel we may not be properly attributing them.

**Comment by batterseapower** [comment]
Agreed. I've fixed this in my fork.
