### ISSUE TITLE
Alternative Dictionary Lookup For Incorrect Entries (Important Fix for Audio)

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#83]
Unfortunately, despite the many, many improvements, 0.05 is a step back from 0.04 in one respect:
incorrect audio generation. For example I recently looked up Motorola, which is a non-dictionary entry. Google translat efound the english, but the pinyin was wrong (I also added it to CEDICT for future ref). Correcting the pinyin is done by manually changing the pinyin and using the color keys (no tonify in this way yet, mentioned in another thread). However the big problem is audio, there is actually now no way to manually add the missing audio files.

In 0.04 if audio was wrong then this could be remedied by just typing the new pinyin and adding a "[sound:.xxx]" tag. This is no longer possible because of checksumming. In fact, it is a serious pain in the bottom to manually add audio to cards in 0.05. For now I am just skipping it for these cards or using F5 and recording myself.

**Comment by batterseapower** [comment]
Hmmm, well.

You can actually still do this by copying a media pack to your media dir and then adding the [sound:] tags, but those sounds won't be the same as the ones used by the automatic audio generation. This isn't a big deal though.

How about this for a feature: we add a hook that does this:
1. You write "ni3 hao3" in the audio field
2. We parse it as pinyin
3. We lookup that pinyin just like it had come from the dictionary
4. We overwrite what you wrote with [sound:ntaeuhnsauhenshu.mp3][sound:ntahunstahuens.mp3] or whatever

If what you typed doesn't parse as pinyin (e.g. if it was just a sequence of [sound:] tags) then we would leave the field alone.

**Comment by batterseapower** [comment]
Should be easy to fix now we have better pinyin parsing. Moving the priority up.

**Comment by Nick3C** [comment]
ah yes, should be easy. But how about we forget doing it this way. Instead we could use your new changes to do it automatically. i.e. edit the reading field, re-pinyin-ise it, and replace the audio at the same time.

Need to be careful of over-wiritng user audio, of course, but otherwise no reason not to do this.

**Comment by batterseapower** [comment]
I implemented the approach described above while I was on the train and hence unable to read your comment :-). Try it out and reopen the ticket if you want to try that alternative instead.

**Comment by Nick3C** [comment]
well what you have done does work but it's not quite as nice because you have to edit both pinyin and audio. Can you reopen it (I don't think I have access rights for that) but make it low priority because there is now a workable solution in place.

**Comment by batterseapower** [comment]
You should be able to reopen it, but the UI sucks. You need to go to "Closed" and open the ticket from there before you have the Open option. I've done it for you for this ticket.
