### ISSUE TITLE
Seperate and Move Menu Items to better Locations

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#85]
post from user JSV:

> There is such interface: Tools -> Pinyin Toolkit -> Preferences.
> Most (but not all) of the settings can be changed there.
> 
> Nick, maybe it would be better to move this command to Settings
> submenu? (Tools submenu is not available until some deck is opened). 

I agree with this, although suggest a slightly different solution. I think we should separate the items and put PYTK setting next to Anki's settings on the settings menu. Mass-fill should be tucked away on the advanced menu (and probably also listed as a button in the preferences window)

**Comment by batterseapower** [comment]
Move Preferences to the Settings menu and avoid exceptions if Tool menu items clicked early. Closed by 45e942b5584de83a535036f49401474aee188871

**Comment by batterseapower** [comment]
I've moved the Preferences menu item to Settings and left the Pinyin Toolkit submenu in Tools. See what you think.

**Comment by Nick3C** [comment]
yes, that's fine I guess.

**Comment by Nick3C** [comment]
there is a clash with the "&t" shortcut though. How about we use a %r (for pReferences) or even &k for "toolKit"

**Comment by batterseapower** [comment]
Changed to &k.
