### ISSUE TITLE
Add Mac Specific Shortcut Keys

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#86]
http://groups.google.com/group/ankisrs/browse_thread/thread/cdc30e69d9a5c2c8/2ad62e7794c58d56?lnk=gst&q=pinyin#2ad62e7794c58d56

> One thing I can't figure out is how to change the tone/color that the 
> plugin generates when it guesses wrong. I'm using OSX, and in the 
> plugin settings it says that I should be able to highlight text and 
> Option-F# for the correct tone, but this brings up system preferences 
> (I'm trying Option-F2). I'm sure I'm missing something simple, so I'll 
> apologize in advance for being silly :). 
> 
> It should be control+F[x]. I don't know anything about macs but if you 
> are you telling me they lack a control key (not the apple key which is 
> equivalent to the windows key) then that is a bit of an issue. There 
> are no obvious (and convenient) free keys to bind those color 

ctrl maps to option on osx. command+fx is probably already taken by 
various system bindings. why not ctrl+shift+num or ctrl+alt+num?

**Comment by Nick3C** [comment]
We can either:
1) change the keys to one of these less nice combinations
2) check if OS-X is running (thus a mac) and if so assign different keys

I find I don't use these keys anywhere near as much as I used to now the bugs in the colorisation are fewer so perhaps a key change? (we could add more custom colors too then)

**Comment by batterseapower** [comment]
I use a Mac and it works for me (in fact, I wrote the code that changed the help text to say Option+Fx on a Mac). I'll take another look though - perhaps he is running Tiger and that has different shortcut keys, or something?

**Comment by batterseapower** [comment]
I've double checked, and the keys certainly work on Leopard. However, one of them (Option+F9?) conflicts with a system function. I think we need to use another shortcut key on Macs (Ctl+F9 is not appropriate because it is used by the system for Spaces switiching).

**Comment by Nick3C** [comment]
We ony use ctrl+f1 through to ctrl+f8 because ctrl+f9 is the html editor in Anki.

**Comment by batterseapower** [comment]
The various Ctrl+FAnything do seem to be bound to stuff on OS X (though I'm not completely sure what some of it is). Perhaps Ctrl+Option+(1-9)? Option+1-9 might be available as well, and is less of a stretch if you need to add Shift for the erhua variant too.

**Comment by Nick3C** [comment]
ctrl-1 to x used to cause problems if Japanese is installed. there was some conflict with damien's custom lookup. might not be an issue now this is in plugins though... (otherwise it would have been my preference).

**Comment by batterseapower** [comment]
I've changed the shortcut to Windows+n on OS X. Lets see how it goes...
