### ISSUE TITLE
Bug with non-core languages

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#87]
reported by user:

> So I tried a different approach: switching the language to Russian and 
> switching off Google translate. This decision proved to be wrong. 
> Although it gave the desired effect, it also gave an undesired one: 
> the plugin started to crash on any attempt to open the Preferences 
> window, with the following traceback: 
> Traceback (most recent call last): 
>   File "/home/jsv/.anki/plugins/pinyin/anki/hooks.py", line 123, in 
>     self.mw.connect(self.action, QtCore.SIGNAL('triggered()'), lambda: 
> self.triggered()) 
>   File "/home/jsv/.anki/plugins/pinyin/anki/hooks.py", line 146, in 
> triggered 
>     controller = 
> pinyin.forms.preferencescontroller.PreferencesController(preferences, 
> self.notifier, self.mediamanager, self.config) 
>   File "/home/jsv/.anki/plugins/pinyin/forms/ 
> preferencescontroller.py", line 46, in **init** 
>     self.updateView() 
>   File "/home/jsv/.anki/plugins/pinyin/forms/ 
> preferencescontroller.py", line 188, in updateView 
>     mapping.updateView() 
>   File "/home/jsv/.anki/plugins/pinyin/forms/ 
> preferencescontroller.py", line 263, in updateView 
>     self.updateViewValue(eval("model." + self.key, { "model" : 
> self.model })) 
>   File "/home/jsv/.anki/plugins/pinyin/forms/ 
> preferencescontroller.py", line 313, in updateViewValue 
>     if utils.fromQVariant(self.combobox.itemData(n)) == value: 
>   File "/home/jsv/.anki/plugins/pinyin/forms/utils.py", line 60, in 
> fromQVariant 
>     raise ValueError, "Could not convert value to %s" % typeName 
> ValueError: Could not convert value to None 
> I had to edit config.db to switch the language back to English. The 
> "manual unpickling" took some time, but as a pleasant side-effect I've 
> found the 'meaninggeneration' option there. After switching it off 
> everything seem to work as expected. :)

**Comment by ghost** [comment]
A bit of clarification.

> switching the language to Russian and switching off Google translate. 

The bug seems to be triggered by choosing any language except English and German (I've tried French, Russian, Esperanto, Quequa and Greek). Other settings like 'fallbackongoogletranslate' and 'meaninggeneration' seem to be irrelevant.

**Comment by batterseapower** [comment]
Handle nulls in QVariant conversion. losed by 3675d24ddfef7c4f2df41f40cd55b406b6e369fb
