### ISSUE TITLE
Error after restarting Anki - Matplotlib not present error

### ISSUE THREAD

**Issue by matrixritter** [batterseapower/pinyin-toolkit#92]
I installed the Toolkit like described in the first step of the readme (1) Click on Anki's "File" -> "Download" -> "Shared Plugin" and select "Pinyin Toolkit"). But after a restart of Anki a window informs me about a plugin error: 

Traceback (most recent call last):
  File "/usr/share/anki/ankiqt/ui/main.py", line 2384, in loadPlugins
    **import**(nopy)
  File "/home/klaus/.anki/plugins/Pinyin Toolkit.py", line 43, in 
    import pinyin.anki.main as main
  File "/home/klaus/.anki/plugins/pinyin/anki/**init**.py", line 2, in 
    import main
  File "/home/klaus/.anki/plugins/pinyin/anki/main.py", line 15, in 
    import statsandgraphs
  File "/home/klaus/.anki/plugins/pinyin/anki/statsandgraphs.py", line 18, in 
    from ankiqt.ui.graphs import AdjustableFigure, GraphWindow
  File "/usr/share/anki/ankiqt/ui/graphs.py", line 12, in 
    from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
ImportError: No module named matplotlib.backends.backend_qt4agg

I am using the recent .deb from Anki (http://ichi2.net/anki/download/files/anki_0.9.9.8.4-1_all.deb)

**Comment by Nick3C** [comment]
It is a problem with matplotlib when trying to initialise Hanzigraph. Linux users have to install it themselves don't they? Do you have it installed? Can you see the normal Anki graphs?

We should be able to add a check on the existance of matplotlib before calling it which should sole the problem (but will mean you can see th pretty graph :)

**Comment by matrixritter** [comment]
Thanks, installing the package "python-matplotlib" (and depending packages) solved the problem of starting error :) This should added to the readme maybe, because ohter Ubuntu-users will experience same.
