### ISSUE TITLE
Unwanted Space Added after Punctuiation

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#94]
Unwanted space added after punctuation

eg1:
(你好)你真么样?
returns ( nǐ hǎo) nǐ zhēn me yàng?

Eg2
苏珊·波伊尔
returns sū shān· bō yī ěr (not in plugin cedict)

**Comment by batterseapower** [comment]
Fix spacing introduced after a bracket. Closed by 5dfaeb8a682911ac7f96fc5c05dc8a67d049b392
