### ISSUE TITLE
Audio Generation Doesn't Use the Sys-Dict leading to Wrong and Inconsistant Readings

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#95]
eg 差 (with latest version in my repository)

pinyin correctly uses sysdict but audio doesn't meaning that audio is not only wrong, but also inconsistent with the pinyin.

**Comment by batterseapower** [comment]
I'm very confused by your report because the pinyin and audio are generated from /identical/ data. Are you sure that you just don't have something wacky for cha1 in one of your sound packs?

**Comment by Nick3C** [comment]
ah, double checked. it doesn't seem to be doing it... could have sworn... anyway, fewer errors is better :)
