### ISSUE TITLE
Characters not found in CEDICT get hanzi in reading field

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#97]
Chinese characters not in CEDICT, eg 噔 deng1 (0.05 dictionary)

 We should check output with the iskanji routine and if it is then no output it into the pin yin field under any circumstances [maybe return the hanzi masking character for unrecognised entries instead]

Note that this is not a moot poin, CEDICT has only 86,328 entries (the majority of which are words not characters) and the most comprehensive chinese dictionary around indicates there are 83,000 CHARACTERS in use. The fact that I just found the above deng1 character shows this is a real-world issue.

**Comment by batterseapower** [comment]
I'm not really sure why we should go to extra trouble to destroy these characters. It's obvious to anyone reading the field that it's not pinyin, and its presence in the reading marks precisely where users need to do a little extra work to find out the correct pinyin themselves. This could be quite helpful when correcting the readings for a sentence with lots of characters not in CEDICT.

Side note: we need to integrate unihan so we can return guesses for the pinyin of many more characters.

**Comment by Nick3C** [comment]
falling back on unihan will solve this adequately...

**Comment by batterseapower** [comment]
Works beautifully with cjklib integration because we can now use reading information from there if there is no CEDICT information.
